### ISSUE TITLE
model failure on generated conformers

### ISSUE THREAD

**Issue by RishalAggarwal** [gcorso/torsional-diffusion#15]
Hey, when I evaluate generated conformers, for some molecules its noted to be a model failure (image attached).

Why do these model failures happen? I can't really place it in the code where these failures take place.
![Screen Shot 2023-07-06 at 10 42 16 AM](https://github.com/gcorso/torsional-diffusion/assets/29447418/6620495b-b528-4688-9e6e-a4a5df7620c4)

**Comment by Curtis-Wu** [comment]
Hi Rishal, did you end up finding out why this happens?

**Comment by RishalAggarwal** [comment]
From what I understand conformer generation failed for that molecule. It could mainly be because of two reasons - problematic smiles string for rdkit to generate conformers or not enough rotatable bonds. Its more usually the former as they model hydrogens explicitly and let any bond type (single/ double or triple) that is not part of a ring be rotatable

**Comment by Curtis-Wu** [comment]
Thanks for the insight!
