### ISSUE TITLE
Set up issue

### ISSUE THREAD

**Issue by brje01** [gcorso/torsional-diffusion#8]
Hi, 
First of all thank you for making your code available. I was curious to test out your conformer generation, but unfortunately ran into a few issues that I was hoping you could help me with. 
A short report on what I did and which errors I ran into (my machine is running Ubuntu 22.04)
- git cloned your repo
- $ conda env create -f environment.yml
- $ conda activate torsional_diffusion
- $ pip install e3nn
- checked the torch and cuda versions: 1.13 and 11.7 (are these the versions you worked with?)
- installed pyg
- $ pip install pyg-lib torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.13.0+cu117.html
- downloaded your workdir, created the smiles.csv
- when running 
$ python generate_confs.py --test_csv smiles.csv --inference_steps 20 --model_dir workdir/drugs_default --out conformers_20steps.pkl --tqdm --batch_size 128 --no_energy
I encountered the following warnings:

../torsional-diffusion/diffusion/torus.py:33: RuntimeWarning: invalid value encountered in divide 
  score_ = grad(x, sigma[:, None], N=100) / p_ 
.../.conda/envs/torsional_diffusion/lib/python3.9/site-packages/torch/jit/_check.py:181: UserWarning: The TorchScript type system doesn't support instance-level annotations on empty non-base types in `__init__`. Instead, either 1) use a type annotation in the class body, or 2) wrap the type in `torch.jit.Attribute`. 
  warnings.warn("The TorchScript type system doesn't support " 
0it [00:00, ?it/s] 
Generated conformers for 0 molecules 

Would you have any idea what might be causing this behaviour?

Thanks in advance for any pointers you can give me and kind regards, 
Jessica

**Comment by corinwagen** [comment]
I also encountered this problem! Same workflow. My ``smiles.csv`` file looks like this:

```
CCCCC, 10, CCCCC
```

Any advice?

**Comment by aksangha** [comment]
I encountered the same issue.

**Comment by Ankeet3** [comment]
I had the same issue. We encounter it because we are generating our own smiles.csv files, and it expects a header for the smiles.csv file. So you can enter a header for your smiles.csv, like "smile_str, num_conformers, smile_str". Another alternative is to go about editing the generate_confs.py file to account for the lack of header in your smiles.csv file.

**Comment by brje01** [comment]
Thanks so much at @Ankeet3 ! I can confirm that that fixed the issue for me as well
